name: Terraform CI

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    name: "SCA & SAST"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x tfsec-linux-amd64
          sudo mv tfsec-linux-amd64 /usr/local/bin/tfsec
      # -soft-fail=false and no continue-on-error.
      # This means if any CIS violation occurs infra job won't execute
      - name: Run tfsec
        run: tfsec .

      - name: Install Checkov
        run: pip install --upgrade checkov==2.2.200

      - name: Run Checkov
        run: checkov -c .checkov.yaml -d .

      - name: Install Trivy
        run: |
          LATEST=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep '"tag_name":' | head -n 1 | cut -d '"' -f4)
          VERSION=${LATEST#v}
          echo "Latest Trivy version: $LATEST"
          wget https://github.com/aquasecurity/trivy/releases/download/${LATEST}/trivy_${VERSION}_Linux-64bit.tar.gz
          tar -xzf trivy_${VERSION}_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy
        run: trivy fs --scanners vuln,secret,config .

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto .

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz
          tar -xzf gitleaks_8.24.3_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks (Secret Detection)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gitleaks detect --source=. --report-path=gitleaks-report.json

  terraform:
    name: "Terraform Workflow"
    runs-on: ubuntu-latest
    needs: security # 👈 security must pass first
    environment: dev # <-- Specify the environment here

    outputs:
      alb_url: ${{ steps.get_alb.outputs.alb_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create SSH public key files
        run: |
          mkdir -p keys
          echo "${{ secrets.WEB_INSTANCE_KEY_PUB }}" > keys/web_instance_key.pub

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ vars.DB_USERNAME }}
          TF_VAR_environment: ${{ vars.ENVIRONMENT }}
          TF_VAR_s3_bucket_with_alb_logs: ${{ vars.S3_BUCKET_WITH_ALB_LOGS }}
          TF_VAR_webapp_instance_key_name: ${{ vars.WEBAPP_INSTANCE_KEY_NAME }}
          TF_VAR_iam_role_name: ${{ secrets.IAM_ROLE_NAME }}
          TF_VAR_iam_user_name: ${{ secrets.IAM_USER_NAME }}
          TF_VAR_backend_state_bucket_name: ${{ vars.BACKEND_STATE_BUCKET_NAME }}
          TF_VAR_dynamodb_state_table_name: ${{ vars.DYNAMODB_STATE_TABLE_NAME }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init

      - name: Run tflint
        run: tflint --disable-rule=terraform_documented_variables

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ vars.DB_USERNAME }}
          TF_VAR_environment: ${{ vars.ENVIRONMENT }}
          TF_VAR_s3_bucket_with_alb_logs: ${{ vars.S3_BUCKET_WITH_ALB_LOGS }}
          TF_VAR_webapp_instance_key_name: ${{ vars.WEBAPP_INSTANCE_KEY_NAME }}
          TF_VAR_iam_role_name: ${{ secrets.IAM_ROLE_NAME }}
          TF_VAR_iam_user_name: ${{ secrets.IAM_USER_NAME }}
          TF_VAR_backend_state_bucket_name: ${{ vars.BACKEND_STATE_BUCKET_NAME }}
          TF_VAR_dynamodb_state_table_name: ${{ vars.DYNAMODB_STATE_TABLE_NAME }}

      - name: Terraform Apply (main branch only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ vars.DB_USERNAME }}
          TF_VAR_environment: ${{ vars.ENVIRONMENT }}
          TF_VAR_s3_bucket_with_alb_logs: ${{ vars.S3_BUCKET_WITH_ALB_LOGS }}
          TF_VAR_webapp_instance_key_name: ${{ vars.WEBAPP_INSTANCE_KEY_NAME }}
          TF_VAR_iam_role_name: ${{ secrets.IAM_ROLE_NAME }}
          TF_VAR_iam_user_name: ${{ secrets.IAM_USER_NAME }}
          TF_VAR_backend_state_bucket_name: ${{ vars.BACKEND_STATE_BUCKET_NAME }}
          TF_VAR_dynamodb_state_table_name: ${{ vars.DYNAMODB_STATE_TABLE_NAME }}

      - name: Get ALB URL from Terraform output (main branch only)
        if: github.ref == 'refs/heads/main'
        id: get_alb
        run: echo "alb_url=$(terraform output -raw alb_dns_name)" >> $GITHUB_OUTPUT

      - name: Wait for ALB to be ready (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          for i in {1..30}; do
            if curl -sSf "http://${{ steps.get_alb.outputs.alb_url }}" ; then
              echo "ALB is ready!"
              exit 0
            else
              echo "Waiting for ALB... ($i/30)"
              sleep 20
            fi
          done
          echo "ALB did not become ready in time."
          exit 1

  dast:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main'
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for ALB to be ready
        run: |
          echo "Waiting for ALB: http://${{ needs.terraform.outputs.alb_url }}"
          for i in {1..30}; do
            if curl -sSf "http://${{ needs.terraform.outputs.alb_url }}" > /dev/null; then
              echo "ALB is ready!"
              exit 0
            else
              echo "Waiting for ALB... ($i/30)"
              sleep 20
            fi
          done
          echo "ALB did not become ready in time."
          exit 1

      - name: Run OWASP ZAP DAST
        id: zap
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://${{ needs.terraform.outputs.alb_url }}"
          fail_action: false
          allow_issue_writing: true
          # disable artifact upload, we'll handle it manually
          upload_artifact: false

      # Explicit artifact upload so you control naming
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-${{ github.run_id }}-${{ github.run_attempt }}
          path: |
            zap-report/*
            owasp-zap-report.html
          if-no-files-found: warn # don't fail if no report is generated
          retention-days: 14

      - name: Add ZAP Report to Job Summary
        if: always() # ensure it runs even if ZAP fails
        run: |
          echo "## OWASP ZAP DAST Report" >> $GITHUB_STEP_SUMMARY
          if [ -f owasp-zap-report.html ]; then
            echo "<details><summary>Click to view ZAP Report</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          # Escape HTML to Markdown-friendly format
            echo '```html' >> $GITHUB_STEP_SUMMARY
            cat owasp-zap-report.html | head -n 200 >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          else
            echo "_No ZAP HTML report was generated._" >> $GITHUB_STEP_SUMMARY
          fi
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    needs: security
    environment: dev
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ vars.DB_USERNAME }}
          TF_VAR_environment: ${{ vars.ENVIRONMENT }}
          TF_VAR_s3_bucket_with_alb_logs: ${{ vars.S3_BUCKET_WITH_ALB_LOGS }}
          TF_VAR_webapp_instance_key_name: ${{ vars.WEBAPP_INSTANCE_KEY_NAME }}
          TF_VAR_iam_role_name: ${{ secrets.IAM_ROLE_NAME }}
          TF_VAR_iam_user_name: ${{ secrets.IAM_USER_NAME }}
          TF_VAR_backend_state_bucket_name: ${{ vars.BACKEND_STATE_BUCKET_NAME }}
          TF_VAR_dynamodb_state_table_name: ${{ vars.DYNAMODB_STATE_TABLE_NAME }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ vars.DB_USERNAME }}
          TF_VAR_environment: ${{ vars.ENVIRONMENT }}
          TF_VAR_s3_bucket_with_alb_logs: ${{ vars.S3_BUCKET_WITH_ALB_LOGS }}
          TF_VAR_webapp_instance_key_name: ${{ vars.WEBAPP_INSTANCE_KEY_NAME }}
          TF_VAR_iam_role_name: ${{ secrets.IAM_ROLE_NAME }}
          TF_VAR_iam_user_name: ${{ secrets.IAM_USER_NAME }}
          TF_VAR_backend_state_bucket_name: ${{ vars.BACKEND_STATE_BUCKET_NAME }}
          TF_VAR_dynamodb_state_table_name: ${{ vars.DYNAMODB_STATE_TABLE_NAME }}
  name: Terraform CI

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    name: "SCA & SAST"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x tfsec-linux-amd64
          sudo mv tfsec-linux-amd64 /usr/local/bin/tfsec
      # -soft-fail=false and no continue-on-error.
      # This means if any CIS violation occurs infra job won't execute
      - name: Run tfsec
        run: tfsec .

      - name: Install Checkov
        run: pip install --upgrade checkov==2.2.200

      - name: Run Checkov
        run: checkov -c .checkov.yaml -d .

      - name: Install Trivy
        run: |
          LATEST=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep '"tag_name":' | head -n 1 | cut -d '"' -f4)
          VERSION=${LATEST#v}
          echo "Latest Trivy version: $LATEST"
          wget https://github.com/aquasecurity/trivy/releases/download/${LATEST}/trivy_${VERSION}_Linux-64bit.tar.gz
          tar -xzf trivy_${VERSION}_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy
        run: trivy fs --scanners vuln,secret,config .

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto .

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz
          tar -xzf gitleaks_8.24.3_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks (Secret Detection)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gitleaks detect --source=. --report-path=gitleaks-report.json

  terraform:
    name: "Terraform Workflow"
    runs-on: ubuntu-latest
    needs: security # 👈 security must pass first
    environment: dev # <-- Specify the environment here

    outputs:
      alb_url: ${{ steps.get_alb.outputs.alb_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create SSH public key files
        run: |
          mkdir -p keys
          echo "${{ secrets.WEB_INSTANCE_KEY_PUB }}" > keys/web_instance_key.pub

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ vars.DB_USERNAME }}
          TF_VAR_environment: ${{ vars.ENVIRONMENT }}
          TF_VAR_s3_bucket_with_alb_logs: ${{ vars.S3_BUCKET_WITH_ALB_LOGS }}
          TF_VAR_webapp_instance_key_name: ${{ vars.WEBAPP_INSTANCE_KEY_NAME }}
          TF_VAR_iam_role_name: ${{ secrets.IAM_ROLE_NAME }}
          TF_VAR_iam_user_name: ${{ secrets.IAM_USER_NAME }}
          TF_VAR_backend_state_bucket_name: ${{ vars.BACKEND_STATE_BUCKET_NAME }}
          TF_VAR_dynamodb_state_table_name: ${{ vars.DYNAMODB_STATE_TABLE_NAME }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init

      - name: Run tflint
        run: tflint --disable-rule=terraform_documented_variables

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ vars.DB_USERNAME }}
          TF_VAR_environment: ${{ vars.ENVIRONMENT }}
          TF_VAR_s3_bucket_with_alb_logs: ${{ vars.S3_BUCKET_WITH_ALB_LOGS }}
          TF_VAR_webapp_instance_key_name: ${{ vars.WEBAPP_INSTANCE_KEY_NAME }}
          TF_VAR_iam_role_name: ${{ secrets.IAM_ROLE_NAME }}
          TF_VAR_iam_user_name: ${{ secrets.IAM_USER_NAME }}
          TF_VAR_backend_state_bucket_name: ${{ vars.BACKEND_STATE_BUCKET_NAME }}
          TF_VAR_dynamodb_state_table_name: ${{ vars.DYNAMODB_STATE_TABLE_NAME }}

      - name: Terraform Apply (main branch only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ vars.DB_USERNAME }}
          TF_VAR_environment: ${{ vars.ENVIRONMENT }}
          TF_VAR_s3_bucket_with_alb_logs: ${{ vars.S3_BUCKET_WITH_ALB_LOGS }}
          TF_VAR_webapp_instance_key_name: ${{ vars.WEBAPP_INSTANCE_KEY_NAME }}
          TF_VAR_iam_role_name: ${{ secrets.IAM_ROLE_NAME }}
          TF_VAR_iam_user_name: ${{ secrets.IAM_USER_NAME }}
          TF_VAR_backend_state_bucket_name: ${{ vars.BACKEND_STATE_BUCKET_NAME }}
          TF_VAR_dynamodb_state_table_name: ${{ vars.DYNAMODB_STATE_TABLE_NAME }}

      - name: Get ALB URL from Terraform output (main branch only)
        if: github.ref == 'refs/heads/main'
        id: get_alb
        run: echo "alb_url=$(terraform output -raw alb_dns_name)" >> $GITHUB_OUTPUT

      - name: Wait for ALB to be ready (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          for i in {1..30}; do
            if curl -sSf "http://${{ steps.get_alb.outputs.alb_url }}" ; then
              echo "ALB is ready!"
              exit 0
            else
              echo "Waiting for ALB... ($i/30)"
              sleep 20
            fi
          done
          echo "ALB did not become ready in time."
          exit 1

  dast:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main'
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for ALB to be ready
        run: |
          echo "Waiting for ALB: http://${{ needs.terraform.outputs.alb_url }}"
          for i in {1..30}; do
            if curl -sSf "http://${{ needs.terraform.outputs.alb_url }}" > /dev/null; then
              echo "ALB is ready!"
              exit 0
            else
              echo "Waiting for ALB... ($i/30)"
              sleep 20
            fi
          done
          echo "ALB did not become ready in time."
          exit 1

      - name: Run OWASP ZAP DAST
        id: zap
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://${{ needs.terraform.outputs.alb_url }}"
          fail_action: false
          allow_issue_writing: true
          # disable artifact upload, we'll handle it manually
          upload_artifact: false

      # Explicit artifact upload so you control naming
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-${{ github.run_id }}-${{ github.run_attempt }}
          path: |
            zap-report/*
            owasp-zap-report.html
          if-no-files-found: warn # don't fail if no report is generated
          retention-days: 14

      - name: Add ZAP Report to Job Summary
        if: always() # ensure it runs even if ZAP fails
        run: |
          echo "## OWASP ZAP DAST Report" >> $GITHUB_STEP_SUMMARY
          if [ -f owasp-zap-report.html ]; then
            echo "<details><summary>Click to view ZAP Report</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          # Escape HTML to Markdown-friendly format
            echo '```html' >> $GITHUB_STEP_SUMMARY
            cat owasp-zap-report.html | head -n 200 >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          else
            echo "_No ZAP HTML report was generated._" >> $GITHUB_STEP_SUMMARY
          fi
